server:
  port: 8081
spring:
  datasource:
        url: jdbc:mysql://localhost:3306/lenos?useUnicode=true&characterEncoding=UTF-8
#        url: jdbc:sqlserver://103.46.128.47:48632;DatabaseName=lenos
#        username: sa
        username: root
        password: 123456
#        password: 123
#        password: l123456
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082

mybatis:
    type-aliases-package: com.len.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.len.base.BaseMapper
    not-empty: false
    identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

lenosp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/lenosp-log.log
  level:
    com.len.mapper: debug

dataType: mysql